apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-kustomization-2
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests
  kubeConfig:
    secretRef:
      name: cluster-attached
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-source-2
  targetNamespace: default